spring:
  application:
    name: user-service
  config:
    import: "optional:configserver:http://config-service:8088"
    activate:
      on-profile: docker

#server:
#  port: 8089
#
#logging:
#  pattern:
#    console: "%d{yyyy-MM-dd HH:mm:ss} [%X{traceId:-},%X{spanId:-}] ${LOG_LEVEL_PATTERN:-%5p} %m%n"
#
#springdoc:
#  packagesToScan: base.service.user
#
#spring:
#  cloud:
#   config:
#    import-check.enabled: false
#  application:
#   name: user-service
#  data:
#    mongodb:
#      host: localhost
#      port: 27017
#      database: test
#
#management:
#  tracing:
#    sampling:
#      probability: 1.0
#
#jwt:
#  secretKey: 8Q54nmxVQMp4ILbZyVFciGXm994uEkJIMCdGXDVqjJsS5qGwBJPDdVuL8Pqkwa
#
#sharing_data:
#  url_appointment: http://${appointment.service.host:localhost}:${appointment.service.port:8080}
#
#eureka:
#  client:
#    register-with-eureka: false
#    fetch-registry: false