version: '3.8'

services:
  mongo_db:
    image: mongo:latest
    ports:
      - '27018:27017'
    restart: always
    volumes:
      - ./docker-entrypoint-initdb.d/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - mongodb_data_container:/data/db

  config-service:
    build: config-service/.
    image: webclient-showcase/config-service:1
    ports:
      - "8088:8088"
    healthcheck:
      test: curl --fail http://localhost:8088/employee/docker  || exit 1
      interval: 5s
      timeout: 2s
      retries: 3
    environment:
      - SERVER_PORT=8088

  discovery-service:
    build: discovery-service/.
    image: webclient-showcase/discovery-service:1
    ports:
      - "8061:8061"
    depends_on:
      config-service:
        condition: service_healthy
    links:
      - config-service
    healthcheck:
      test: curl --fail http://localhost:8061/eureka/v2/apps || exit 1
      interval: 4s
      timeout: 2s
      retries: 3
    environment:
      - SERVER_PORT=8061
      - SPRING_PROFILES_ACTIVE=docker

  employee-service:
    build: employee-service/.
    image: webclient-showcase/employee-service:1
    ports:
      - "8001:8001"
    depends_on:
      config-service:
        condition: service_healthy
    links:
      - config-service
    environment:
      - SERVER_PORT=8001
      - SPRING_PROFILES_ACTIVE=docker

  treatment-service:
    build: treatment-service/.
    image: webclient-showcase/treatment-service:1
    ports:
      - "8002:8002"
    depends_on:
      config-service:
        condition: service_healthy
    links:
      - config-service
    environment:
      - SERVER_PORT=8002
      - SPRING_PROFILES_ACTIVE=docker

  user-service:
    build: user-service/.
    image: webclient-showcase/user-service:1
    ports:
      - "8003:8003"
    depends_on:
      config-service:
        condition: service_healthy
    links:
      - config-service
    environment:
      - SERVER_PORT=8003
      - SPRING_PROFILES_ACTIVE=docker
      - APPOINTMENT_SERVICE_HOST=appointment-service
      - APPOINTMENT_SERVICE_PORT=8004

  appointment-service:
    build: appointment-service/.
    image: webclient-showcase/appointment-service:1
    ports:
      - "8004:8004"
    depends_on:
      config-service:
        condition: service_healthy
    links:
      - config-service
    environment:
      - SERVER_PORT=8004
      - SPRING_PROFILES_ACTIVE=docker
      - EMPLOYEE_SERVICE_HOST=employee-service
      - EMPLOYEE_SERVICE_PORT=8001
      - TREATMENT_SERVICE_HOST=treatment-service
      - TREATMENT_SERVICE_PORT=8002

  gateway-service:
    build: gateway-service/.
    image: webclient-showcase/gateway-service:1
    ports:
      - "8060:8060"
    depends_on:
      config-service:
        condition: service_healthy
    links:
      - config-service
      - discovery-service
      - user-service
      - employee-service
      - treatment-service
      - appointment-service
    environment:
      - SERVER_PORT=8060
      - SPRING_PROFILES_ACTIVE=docker

volumes:
  mongodb_data_container: