eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-service:8061/eureka/

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%X{traceId:-},%X{spanId:-}] ${LOG_LEVEL_PATTERN:-%5p} %m%n"

spring:
  output:
    ansi:
      enabled: always
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedHeaders: "*"
            allowedMethods: "*"
      discovery:
        locator:
          enabled: true
      routes:
        - id: appointment-service
          uri: lb://appointment-service
          predicates:
            - Path=/appointments/**
          filters:
            - RewritePath=/appointments/(?<path>.*), /$\{path}
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/user/**
          filters:
            - RewritePath=/user/(?<path>.*), /$\{path}
        - id: employee-service
          uri: lb://employee-service
          predicates:
            - Path=/employees/**
          filters:
            - RewritePath=/employees/(?<path>.*), /$\{path}
        - id: treatment-service
          uri: lb://treatment-service
          predicates:
            - Path=/treatments/**
          filters:
            - RewritePath=/treatments/(?<path>.*), /$\{path}
        - id: openapi
          uri: http://localhost:${server.port}
          predicates:
            - Path=/v3/api-docs/**
          filters:
            - RewritePath=/v3/api-docs/(?<path>.*), /$\{path}/v3/api-docs

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    urls:
      - name: user
        url: /v3/api-docs/user
      - name: employees
        url: /v3/api-docs/employees
      - name: treatments
        url: /v3/api-docs/treatments
      - name: appointments
        url: /v3/api-docs/appointments

management:
  tracing:
    sampling:
      probability: 1.0